### PR TITLE
Rhel support

### PR DESCRIPTION
**Pull request by taylor-benson**
Added support for RHEL linux families

### CODE REVIEW

**Comment by patrickayoup** [comment]
@taylor-benson 

Thank you for your contribution. I am no longer using Chef and therefore am not interested in maintaining this project anymore.

Please see #9 

If you would like to have this merged, I will offer you ownership of this repository so it doesn't simply become abandoned.

**Comment by taylor-benson** [comment]
I would be happy to become the maintainer. Let me know.

**Comment by patrickayoup** [comment]
@taylor-benson

You got it, I'll need your chef supermarket username and I'll do the transfer today.

Thanks!

**Comment by patrickayoup** [comment]
@taylor-benson Do you have an update on this?

**Comment by taylor-benson** [comment]
Sorry I got swamped with coding at work and home life with the kids, I'll
create a supermarket account tonight

**Comment by taylor-benson** [comment]
Here you go https://supermarket.chef.io/users/taylor-benson

Thanks for letting me get involved.

Never published anything in the open community so looking forward to it.

**Comment by patrickayoup** [comment]
Done. I initiated the transfer on supermarket. I believe you were sent a notification and all you need to do is accept and it's all yours. Thanks

**Pull request merged**
